// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[] args) {
		int runNum = Integer.parseInt(args[0]);
		double ran;
		int under = 0;
		int above = 0;
		for (int i = 0; i < runNum; i++) {
			ran = Math.random();
			if (ran <= 0.5) {
				under++;
			} 
			else {
				above++;
			}
		}
		double ratio = ((double) Math.min(under, above) / Math.max(under, above));
		System.out.println("<= " + under + "\n" + "> " + above + "\n Ratio: " + ratio);
	}
}
